package utpb.team8.eventviewer;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;
import android.widget.ImageButton;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Environment;
import android.provider.MediaStore;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;

/*When an album listing is expanded this class controls the corresponding individual album page
Each individual album page will load different information but it will all be loaded in the same way as defined in this class
 */
public class AlbumDetailActivity extends AppCompatActivity {
    //String[] nameArray = {"Lunch","THOR","Football","Project Meeting"};
    //Integer[] imageArray = {R.drawable.lunch1, R.drawable.lunch2, R.drawable.lunch3, R.drawable.lunch4};
    String [] nameArray;
    int[] imagesArrayPre;
    Integer[] imageArray;

    ImageButton camera;

    ListView listView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_album_detail);

        Bundle extras = getIntent().getExtras();

        final String eventTitle = extras.getString("Title");
        TextView myTitle = (TextView) findViewById(R.id.albumName);
        myTitle.setText(eventTitle);

        nameArray = extras.getStringArray("Names");
        imagesArrayPre = extras.getIntArray("Album");

        imageArray = new Integer[imagesArrayPre.length];
        for(int i = 0; i < imagesArrayPre.length; i++)
        {
          imageArray[i] = imagesArrayPre[i];
        }

        AlbumDetailAdapter albumDetail = new AlbumDetailAdapter(this, nameArray, imageArray);
        listView = (ListView) findViewById(R.id.albumDetailListView);
        listView.setAdapter(albumDetail);

        camera = (ImageButton) findViewById(R.id.addToAlbum);
        camera.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(AlbumDetailActivity.this, ImageUpload.class);
                String calledBy = "album";
                //go back and make this generated by what was typed in by the user
                String definition = eventTitle;

                intent.putExtra("CalledBy", calledBy);
                intent.putExtra("Definition", definition);
                startActivity(intent);
            }
        });

    }


}