package utpb.team8.eventviewer;
import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.media.Image;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.ImageView;


/*This class is used to gather user input from the CreateEvent page and insert it into the database as a new event
 */
public class CreateEvent extends Fragment {

    EditText title;
    EditText details;
    EditText date;
    Button set;
    Button submit;
    ImageButton camera;

    String titleString;
    String detailsString;
    String dateString;
    ImageView image;

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        //returning our layout file
        //change R.layout.yourlayoutfilename for each of your fragments
        return inflater.inflate(R.layout.fragment_create_event, container, false);
    }


    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        //you can set the title for your toolbar here for different fragments different titles
        getActivity().setTitle("Create Event");

        title = getView().findViewById(R.id.createTitle);
        details = getView().findViewById(R.id.createDetails);
        date = getView().findViewById(R.id.createDate);

        image = getView().findViewById(R.id.eventImageCreate);

        set = (Button) getView().findViewById(R.id.set);
        set.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view){
                getInformation(title, details, date);
            }

        });

        camera = (ImageButton) getView().findViewById(R.id.createEventImage);
        camera.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(getActivity(), ImageUpload.class);
                String calledBy = "create";
                //go back and make this generated by what was typed in by the user
                String definition = titleString;

                intent.putExtra("CalledBy", calledBy);
                intent.putExtra("Definition", definition);
                startActivityForResult(intent, 1);
            }
        });

        submit = (Button) getView().findViewById(R.id.submit);
        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                uploadToDatabase(titleString, detailsString, dateString, image);
            }
        });
    }


    private void getInformation(EditText title, EditText details, EditText date) {

        titleString = title.getText().toString();
        detailsString = details.getText().toString();
        dateString = date.getText().toString();


    }

    private void uploadToDatabase(String titleString, String detailsString, String dateString, ImageView image) {
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data){
        if(requestCode == 1){
            if(resultCode == Activity.RESULT_OK){
                Bitmap result = data.getParcelableExtra("result");
                image.setImageBitmap(result);
            }
            if(resultCode == Activity.RESULT_CANCELED){
                //nothing happens
            }
        }
    }

}
